approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  '@commitlint/cli@*':
    dependencies:
      '@types/node': '*'
      typescript: '>=5'
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '>=5'

npmMinimalAgeGate: 0
