# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Handling Reading
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  '.editorconfig',
  'node_modules',
  'vendor/bundle/',
  'vendor/cache/',
  'vendor/gems/',
  'vendor/ruby/',
]
keep_files: ['.git', '.svn']
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

# Plugins
plugins: [
  'jekyll-feed',
  'jekyll-sitemap'
]

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: "/:title/"
sitemap: true
sass:
    style: :compressed

# Other setting
domain: deeppines.github.io
url: "https://deeppines.github.io" # the base hostname & protocol for your site, e.g. http://example.com
title: deeppines
description: Записная книжка одного HTML/CSS кодера
author: deeppines
email: atheus92@gmail.com

github:
    username: deeppines

collections:
  projects:
    output: true
